### ISSUE TITLE
Month and day of the week seems to be inverted.

### ISSUE THREAD

**Issue by sfarfarini** [jacobscarter/angular-cron-jobs#11]
After some try I discovered, according to fromCron, that the cron string is parsed as `m h D w M y`, but, according to crontab documentation, should be `m h D M w y`.
This generates weekly task which results in invalid cron.

The generated cron seems to suffer of the same issue.

**Comment by jacobscarter** [comment]
@sfarfarini the cron output is [minute, hour, day of the month, month, day of the week] as specified in the sources below.

[WIKI](http://en.wikipedia.org/wiki/Cron)
[Cron Tab](http://www.adminschoice.com/crontab-quick-reference)
[nnCron](http://www.nncron.ru/help/EN/working/cron-format.htm)
