### ISSUE TITLE
Why same cron expression for “Every Minute”, “Every Hour at 0 past hour”,“Every Day at 0:0” etc

### ISSUE THREAD

**Issue by vinhnghi223** [jacobscarter/angular-cron-jobs#12]
I have also put the same question here on StackOverflow:
http://stackoverflow.com/questions/30773885/why-angular-cron-jobs-generates-the-same-cron-expression-for-every-minute-ev

**Comment by jacobscarter** [comment]
This was a problem with the Demo using an older version on angular-cron-jobs.  The newer versions corrected this issue.  I also updated the demo http://jacobscarter.github.io/angular-cron-jobs/#/
