### ISSUE TITLE
options' values' types are inconsistent

### ISSUE THREAD

**Issue by DmitryEfimenko** [jacobscarter/angular-cron-jobs#13]
First thing is first - awesome work!

Now the issue: I'm trying to create a different template using [angular-material](https://material.angularjs.org) and therefore converting all `<select>` elements into `<md-select>`

It appears that angular's `select` directive is more forgiving on the values, which is why code works for the default template. However, angular-materials directive is having troubles because of the [lines like below and similar](https://github.com/jacobscarter/angular-cron-jobs/blob/master/src/cronService.js#L18):
```
if(n && n.base && n.base === '4') {
```
It seems that all values are initially declared as integers. However, in the if statements the comparison uses string value. This should be:
```
if(n && n.base && n.base === 4) {
```

**Comment by jacobscarter** [comment]
Hi @dmitriefimenko. This issue has popped up several times :/ the variables are changes to number, strings and back. While in the service they are strings and while in the directive they are integers if I'm remembering correctly. Either way I will take a look and find a way to make it consistent. Either only strings or only numbers. Could you post a fiddle or plunkr with some code for your issue? While the vars do change to strings and numbers and back the code accommodates for this so it shouldn't be throwing an error. Thanks!

**Comment by DmitryEfimenko** [comment]
Here is a [Plunker](http://plnkr.co/edit/tM8brG8iyi1yiF2ztn85?p=preview)
Notice that for the template it's using this [codepen](http://codepen.io/anon/pen/OVjBVN).
To see the issue, select Week in the first dropdown.
The output should be `0 0 * * 0`, but it is `0 0 * * *`

**Comment by jacobscarter** [comment]
So turns out the root of the problem was the ng-options in the select.  I recreated the $scope.frequency to be an array of objects.  This allows the selection of an option to translate to a numeric value rather than a string so we can keep $scope.myFrequency.base as a number throughout the whole process rather than switching back and forth.  Here is your [Plunkr](http://plnkr.co/edit/TgYPUY816iSWh81scGko) with the updated version (1.3.2) and it is working.  Thanks for bringing this up!  You can update your bower.json to include the latest version and you should be good to go!

**Comment by DmitryEfimenko** [comment]
Confirming that it works.
For these who want to use angular-material template, here it is (no extra css needed):
```html
<div class="cron-wrap">
    <span>Every: </span>
    <md-select class="cron-select" ng-model="myFrequency.base">
        <md-option ng-value="opt.value" ng-repeat="opt in frequency">{{opt.label}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base == 4"> on </span>
    <md-select ng-show="myFrequency.base == 4" class="cron-select day-value" ng-model="myFrequency.dayValue">
        <md-option ng-value="opt" ng-repeat="opt in dayValue">{{opt | dayName}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base >= 5"> on the </span>
    <md-select ng-show="myFrequency.base >= 5" class="cron-select day-of-month-value" ng-model="myFrequency.dayOfMonthValue">
        <md-option ng-value="opt" ng-repeat="opt in dayOfMonthValue">{{opt | numeral}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base == 6"> of </span>
    <md-select ng-show="myFrequency.base == 6" class="cron-select month-value" ng-model="myFrequency.monthValue">
        <md-option ng-value="opt" ng-repeat="opt in monthValue">{{opt | monthName}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base >= 2"> at </span>
    <md-select ng-show="myFrequency.base >= 3" class="cron-select hour-value" ng-model="myFrequency.hourValue">
        <md-option ng-value="opt" ng-repeat="opt in hourValue">{{opt}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base >= 3"> : </span>
    <md-select ng-show="myFrequency.base >= 2" class="cron-select minute-value" ng-model="myFrequency.minuteValue">
        <md-option ng-value="opt" ng-repeat="opt in minuteValue">{{opt}}</md-option>
    </md-select>
    <span ng-show="myFrequency.base == 2"> past the hour</span>
</div>
```
You might even add it to docs if you'd like.

Now, this is a bit off topic, but I saw in the "Coming Soon" section about more complicated UI planned. Could you elaborate what you have in mind?

**Comment by jacobscarter** [comment]
@DmitryEfimenko ability to do things like select multiple days of the week, etc.
