### ISSUE TITLE
Allow list of values for fields

### ISSUE THREAD

**Issue by georgewhewell** [jacobscarter/angular-cron-jobs#15]
Hi- great directive, thanks!

It would be useful to be able to use a multi-select for the second input field, so multiple days could be selected if 'Every Week' is selected, or multiple months selected if 'Every Year'.

**Comment by jacobscarter** [comment]
Plan on making this a part of the next release.  Thanks.

**Comment by TimPietrusky** [comment]
+1

**Comment by mosounov** [comment]
Did this ever make it into master?

**Comment by TimPietrusky** [comment]
+1

**Comment by jacobscarter** [comment]
This is being addressed in PR #31 I will get it merges ASAP.

**Comment by jacobscarter** [comment]
@TimPietrusky @mosounov @georgewhewell  I am about to release version 2.0.0.  The reason for the major version number increase is that custom templates made for version 1.4.2 may not work with this new version.  

Version 2.0.0 will support multiselect, please view README.md, CHANGELOG.md, and the Demo page to see multiselect in action.

Selections such as "Every Five Minutes" or "Last Thursday of Every Month" will be a part of the next minor release for version 2.

Thanks!
