### ISSUE TITLE
[FEATURE REQUEST ] Support ranges and lists

### ISSUE THREAD

**Issue by QuantumInformation** [jacobscarter/angular-cron-jobs#21]
Would it be possible to add support for ranges in times and lists eg 0-4.

A list would be:

1/3/5 * * * * 

would be every 1st, 3rd and 5th minute.

**Comment by stalluri** [comment]
Would love to get cron expressions for every 5 min, every 10 min, every 15 min type of use-cases

**Comment by QuantumInformation** [comment]
Can this be closed?

**Comment by mosounov** [comment]
Was this ever implemented?

**Comment by QuantumInformation** [comment]
Don't think so.

**Comment by pjatinsight** [comment]
Is this what would be needed to support 

  0 22 * * 1-5

Which I believe is 10pm every weekday?

**Comment by mosounov** [comment]
Yes, ad perhaps something like: every 5 minutes
*/5 * * * *

**Comment by jacobscarter** [comment]
Is anyone willing to make a PR for this? If not I will try and get it in by 1.6.0

**Comment by jacobscarter** [comment]
@mosounov @QuantumInformation @pjatinsight @stalluri  I am about to release version 2.0.0. The reason for the major version number increase is that custom templates made for version 1.4.2 may not work with this new version.

Version 2.0.0 will support multiselect, e.g

`35 1 1,4,7 *`

 please view README.md, CHANGELOG.md, and the Demo page to see multiselect in action.

Selections such as "Every Five Minutes" or "Last Thursday of Every Month" will be a part of the next minor release for version 2.

Thanks!
