### ISSUE TITLE
allow validation

### ISSUE THREAD

**Issue by DmitryEfimenko** [jacobscarter/angular-cron-jobs#22]
Currently the `output` property for the `cron-selection` will default to `* * * * *` even if nothing is selected. That does not seem like the right behavior.
Some forms might require cron to be selected. Others might not.
Because it's defaulted to a value, there is no way to enforce `required` validation.

Also, on a side note (this should have been a separate issue), what's the reason for separating attributes `init` and `output`?
I haven't came across a situation when I'd need to bind these to different props. Why not combine them into `ng-model`?

**Comment by jacobscarter** [comment]
Should have this updated by Sunday.  Thanks.

**Comment by jacobscarter** [comment]
@DmitryEfimenko init and output become different as soon as the user changes the initial value.

In regards to you validation, is that something you would be willing to make a PR for?

**Comment by DmitryEfimenko** [comment]
the reason I asked about splitted `init` and `output` is that it does not follow current paradigm of any angular inputs. Usually an input has `ngModel`. If a developer wants to record the initial value, he does so during the component initialization.
You really never use init on its own. It's only used to set initial values. Then you forget about it and use the output.
Merging these two will simplify api and make the whole thing more intuitive.
I could work on merging them.

**Comment by jacobscarter** [comment]
@DmitryEfimenko  Yes that makes a lot of sense, I agree with you, if you get a PR up I will merge it, otherwise I will get to it as soon as I can.
