### ISSUE TITLE
expose base and possibly other parts

### ISSUE THREAD

**Issue by DmitryEfimenko** [jacobscarter/angular-cron-jobs#23]
I have a case when I need to know what `base` user selected. I know that internally there is a variable for that, but maybe we could expose this info to the `outside`?
While we are at it, perhaps it would be a good idea to also expose other potentially useful stuff.
What do you think about it?

**Comment by DmitryEfimenko** [comment]
If we come to an agreement about api for this, I could start working on a PR.
Let me know.

**Comment by jacobscarter** [comment]
What other ideas do you have for what to expose and what ideas do you have for implementation?

I'd love to hear them.

**Comment by DmitryEfimenko** [comment]
perhaps the whole `myFrequency` object could be exposed since there might be a need to find out which value for a given input was selected.

As for the implementation, it is already on the scope. One would only have to add two-way binding property to the scope of the directive and call it done.

**Comment by jacobscarter** [comment]
I will get this into the next push, hoping to  be caught up by Sunday.  Thanks!

**Comment by jacobscarter** [comment]
@DmitryEfimenko are you still willing to make a PR for this?

**Comment by jacobscarter** [comment]
@DmitryEfimenko awesome thanks, can you do me a favor and not commit the dist folder, I will build it and release new versions to bower and npm once I merge the source.

Thanks!
