### ISSUE TITLE
Additional comma after Saturday

### ISSUE THREAD

**Issue by ntsim** [jacobscarter/angular-cron-jobs#25]
Quick fix, for lines 208-216, there is an additional comma after day 'Saturday' in .filter('dayName', ...).

This is problematic as it's obviously not great syntactically but it also makes Closure compiler fail.

**Comment by jacobscarter** [comment]
Okay I will add this to the fixes of the next release, hoping to get caught up by Sunday.

Thanks for pointing it out!

**Comment by jacobscarter** [comment]
Fixed in 1.4.2
