### ISSUE TITLE
Is there a way to set after init has happened?

### ISSUE THREAD

**Issue by kgividen** [jacobscarter/angular-cron-jobs#3]
Is there a way to update the cron data after it's already been initialized? 

For example after a new file is loaded from disk I'd like to update the cron with the data from the file but I'm not sure if this is currently possible.  

I know the first time it renders it will render with cronInitData but I don't see a way to set the data after it's been initialized once.

Thanks.

**Comment by jacobscarter** [comment]
@kgividen I will add this functionality as soon as I can.  Thanks

**Comment by TimPietrusky** [comment]
+1

**Comment by jacobscarter** [comment]
Just pushed version 1.3.0.  There is a property called `reset`.  You can pass an expression into here.  The directive is watching that expression and anytime is changes and passes the `angular.isDefined()` method the cron will reset itself to match that value, example below and in the README.md file:

```
//controller
$scope.pushMe = function(){
    $scope.myReset = "0 0 * * *";
}

//partial
<cron-selection reset="{{myReset}}"></cron-selection>

<button ng-click="pushMe()">Click Here</button>
```

**Comment by TimPietrusky** [comment]
Awesome! But why don't you combine the `init` / `reset` attributes?

**Comment by jacobscarter** [comment]
Good idea, I'll leave this open until I get around to fixing it

**Comment by TimPietrusky** [comment]
Awesome! Thanks for doing this!

**Comment by jacobscarter** [comment]
Updated with version 1.3.1
