### ISSUE TITLE
styling of dropdowns in Firefox

### ISSUE THREAD

**Issue by astewes** [jacobscarter/angular-cron-jobs#30]
Firefox's native styling of select dropdowns looks very "off." If we can have the provision to wrap each select dropdown with a parent, it would make custom styling much easier.

![screen shot 2015-10-14 at 11 59 31 am](https://cloud.githubusercontent.com/assets/5335210/10494462/55ef6fd6-726b-11e5-8899-888b8bc97651.png)

**Comment by jacobscarter** [comment]
Will release in 1.4.2, PR merged for this feature.
