### ISSUE TITLE
How would i convert the output string to ISO 8601 syntax format

### ISSUE THREAD

**Issue by GaurangGhinaiya** [jacobscarter/angular-cron-jobs#32]
Hi everyone.
I would like to convert output string as ISO 8601 syntax format.

For example every minute would be "R/P1M" insted of * * * * *
Thanks

**Comment by jacobscarter** [comment]
Hi @GaurangGhinaiya an Angular $filter could probably achieve this, I do not know of one off the top of my head.  Because this isn't a feature of angular-cron-jobs directive I am going to close the issue.  However it is a good suggestion for a new directive for someone to make!
