### ISSUE TITLE
Ability to use a custom template.

### ISSUE THREAD

**Issue by TimotheeJeannin** [jacobscarter/angular-cron-jobs#4]
It would be great to be able to use a custom template. 
I cannot integrate this into my website because I need support for foreign languages and support for custom design. 

Maybe allow something like this ?

```html
<cron-selection output="myOutput">
    <my-custom-html-here>
        Custom html that comply with angular-cron-jobs requirements
        that also includes my design and translations. 
    </my-custom-html-here>
</cron-selection>
```

Thank you for your awesome work ! :)

**Comment by TimotheeJeannin** [comment]
In fact it looks like it is possible using the `template` attribute.

```javascript
templateUrl: function(element, attributes) {
    return attributes.template || 'cronselection.html';
},
```

It is just not documented. Maybe add this in the documentation ?

**Comment by jacobscarter** [comment]
It has been added, thanks a bunch!
