### ISSUE TITLE
v2.0.0 broke init functionality

### ISSUE THREAD

**Issue by DmitryEfimenko** [jacobscarter/angular-cron-jobs#41]
While working on merging init and output I noticed that ever since v2.0.0, the init does not work because of the changes to `cronService.fromCron()` function.

**Steps to reproduce:**
* select base;
* trigger init value change in the model
* observe that inputs didn't get populated properly

Particularly, it seems that if's failing because of lines line that:
```javascript
frequency.minuteValue = [parseInt(cron[0])];
```
... where the parsed value is wrapped in an array.

Not sure if this is a known "work in progress" situation or not, so I'm wondering if I should poke around this or let you fix this one and proceed with my stuff after.

**Comment by jacobscarter** [comment]
Hi @DmitryEfimenko thanks for pointing this out, the parsed values are being wrapped in array to support the multi-select, I can either update the documentation to show that init values must now be `Array.<number>` or you can include that in your init output merge PR if you are close to finished with that.  Let me know.

**Comment by raamtg** [comment]
omg thank you sooooo much for this fix!
