### ISSUE TITLE
Every day at midnight produces incorrect cron string

### ISSUE THREAD

**Issue by TSteele27** [jacobscarter/angular-cron-jobs#9]
if you try to do every day at midnight (0 minutes 0 hour) the cron string is * * * * * it should be:
 00 00 * * *

**Comment by TSteele27** [comment]
It seems this issue is caused by the set cron function:
the 0 values evaluate to false and the string gets set to *
service.setCron = function(n) {
        var cron = ['*', '*', '*',  '*',  '*'];

        if(n && n.base && n.base >= '2') {
            cron[0] = n.minuteValue || '*';
        }

        if(n && n.base && n.base >= '3') {
            cron[1] = n.hourValue || '*';
        }

        if(n && n.base && n.base === '4') {
            cron[4] = n.dayValue;
        }

        if(n && n.base && n.base >= '5') {
            cron[2] = n.dayOfMonthValue || '*';
        }

        if(n && n.base && n.base === '6') {
            cron[3] = n.monthValue || '*';
        }

        return cron.join(' ');
    };

**Comment by jacobscarter** [comment]
Fixed with your PR, thanks!
